# .streamlit/secrets.toml

SUPABASE_URL = "https://hylhbsrckmygluiykdur.supabase.co/rest/v1/"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5bGhic3Jja215Z2x1aXlrZHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MDEzOTUsImV4cCI6MjA5NTk3NzM5NX0.kUieh81kKnyZwzRa5sgmRDAIbEGg2xDMt1CGvf4RBnw"

BUCKET_IMAGENS = "imagens-bgr"
BUCKET_BGR = "arquivos-bgr"
