SPREADSHEET_ID = "ID_DA_SUA_PLANILHA_AQUI"

[gcp_service_account]
type = "service_account"
project_id = "seu_project_id"
private_key_id = "sua_private_key_id"
private_key = "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n"
client_email = "sua_conta@projeto.iam.gserviceaccount.com"
client_id = "seu_client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
